name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install
        run: yarn install
        env:
          CI: true
      - name: build
        run: yarn build
      - name: test
        run: yarn test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
